name: Continuous Integration

on: push

jobs:
  build_test:
    name: Build and Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test:coverage -- --runInBand
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: jest
          token: ${{ secrets.CODECOV_TOKEN }}
  cypress:
  runs-on: ubuntu-latest
  strategy:
    fail-fast: false
    matrix:
      containers: [1, 2, 3]
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18' # or whatever you're using

    - name: Install Dependencies
      run: npm ci

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        start: npm start
        wait-on: 'http://localhost:8080'
        working-directory: . # change this if Cypress is in a subfolder
        record: ${{ !!secrets.CYPRESS_RECORD_KEY }}
        parallel: ${{ !!secrets.CYPRESS_RECORD_KEY }}
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CODE_COVERAGE: true
        CYPRESS_coverage: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        flags: cypress
        token: ${{ secrets.CODECOV_TOKEN }}
  s3-deploy:
    name: S3 Deploy
    needs:
      - build_test
      - cypress
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_type == 'branch' && 'development' || 'staging' }}
      url: https://models-resources.concord.org/new-repository/${{ steps.s3-deploy.outputs.deployPath }}/index.html
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
        env:
          # skip installing cypress since it isn't needed for just building
          # This decreases the deploy time quite a bit
          CYPRESS_INSTALL_BINARY: 0
      - uses: concord-consortium/s3-deploy-action@v1
        id: s3-deploy
        with:
          bucket: models-resources
          prefix: new-repository
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Parameters to GHActions have to be strings, so a regular yaml array cannot
          # be used. Instead the `|` turns the following lines into a string
          topBranches: |
            ["main"]