name: Continuous Integration

on: push

jobs:
  build_test:
    name: Build and Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test:coverage -- --runInBand
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: jest
          token: ${{ secrets.CODECOV_TOKEN }}
  s3-deploy:
    name: S3 Deploy
    needs:
      - build_test
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_type == 'branch' && 'development' || 'staging' }}
      url: https://models-resources.concord.org/new-repository/${{ steps.s3-deploy.outputs.deployPath }}/index.html
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
        env:
          # skip installing cypress since it isn't needed for just building
          # This decreases the deploy time quite a bit
          CYPRESS_INSTALL_BINARY: 0
      - uses: concord-consortium/s3-deploy-action@v1
        id: s3-deploy
        with:
          bucket: models-resources
          prefix: new-repository
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Parameters to GHActions have to be strings, so a regular yaml array cannot
          # be used. Instead the `|` turns the following lines into a string
          topBranches: |
            ["main"]